/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.artags.android.app;

public final class R {
    public static final class array {
        public static final int ar_browsers_entries=0x7f050000;
        public static final int ar_browsers_entryvalues=0x7f050001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int background=0x7f020000;
        public static final int background_artags=0x7f020001;
        public static final int background_land=0x7f020002;
        public static final int bt_display=0x7f020003;
        public static final int bt_display_down=0x7f020004;
        public static final int bt_draw=0x7f020005;
        public static final int bt_draw_down=0x7f020006;
        public static final int credits=0x7f020007;
        public static final int icon=0x7f020008;
        public static final int marker=0x7f020009;
        public static final int menu_blur=0x7f02000a;
        public static final int menu_brush=0x7f02000b;
        public static final int menu_color=0x7f02000c;
        public static final int menu_credits=0x7f02000d;
        public static final int menu_emboss=0x7f02000e;
        public static final int menu_erase=0x7f02000f;
        public static final int menu_eyedropper=0x7f020010;
        public static final int menu_mylocation=0x7f020011;
        public static final int menu_preferences=0x7f020012;
        public static final int menu_reset=0x7f020013;
        public static final int menu_save=0x7f020014;
        public static final int menu_send=0x7f020015;
        public static final int menu_undo=0x7f020016;
        public static final int progress=0x7f020017;
        public static final int splash=0x7f020018;
        public static final int splash_land=0x7f020019;
    }
    public static final class id {
        public static final int brush_size=0x7f080005;
        public static final int button_display=0x7f080014;
        public static final int button_draw=0x7f080013;
        public static final int button_ok=0x7f080009;
        public static final int checkbox_landscape=0x7f08000d;
        public static final int color_intensity=0x7f080001;
        public static final int credits=0x7f080000;
        public static final int dialog_title=0x7f08000a;
        public static final int displayartImageView01=0x7f080012;
        public static final int edit_title=0x7f08000c;
        public static final int label_title=0x7f08000b;
        public static final int mylocation_address=0x7f08001d;
        public static final int mylocation_address_title=0x7f08001c;
        public static final int mylocation_cancel_button=0x7f080024;
        public static final int mylocation_detect_title=0x7f080017;
        public static final int mylocation_form=0x7f080019;
        public static final int mylocation_get_position_button=0x7f08001b;
        public static final int mylocation_latitude=0x7f08001f;
        public static final int mylocation_latitude_label=0x7f08001e;
        public static final int mylocation_layout=0x7f080015;
        public static final int mylocation_longitude=0x7f080021;
        public static final int mylocation_longitude_label=0x7f080020;
        public static final int mylocation_progress=0x7f080018;
        public static final int mylocation_select_source_button=0x7f08001a;
        public static final int mylocation_title=0x7f080016;
        public static final int mylocation_validate=0x7f080022;
        public static final int mylocation_validate_button=0x7f080023;
        public static final int opacity=0x7f080003;
        public static final int preferences_browser=0x7f080029;
        public static final int preferences_browser_label=0x7f080028;
        public static final int preferences_browser_title=0x7f080027;
        public static final int preferences_button_change_browser=0x7f08002a;
        public static final int preferences_button_close=0x7f08002d;
        public static final int preferences_checkbox_mylocation=0x7f08002c;
        public static final int preferences_layout=0x7f080025;
        public static final int preferences_location_title=0x7f08002b;
        public static final int preferences_title=0x7f080026;
        public static final int seek_brush_size=0x7f080006;
        public static final int seek_intensity=0x7f080002;
        public static final int seek_opacity=0x7f080004;
        public static final int send_cancel_button=0x7f080011;
        public static final int send_search_location=0x7f08000e;
        public static final int send_search_location_progress=0x7f08000f;
        public static final int send_send_button=0x7f080010;
        public static final int splash=0x7f08002e;
        public static final int toggleBlur=0x7f080008;
        public static final int toggleEmboss=0x7f080007;
        public static final int webview=0x7f08002f;
    }
    public static final class layout {
        public static final int credits=0x7f030000;
        public static final int dialog_brush=0x7f030001;
        public static final int dialog_send=0x7f030002;
        public static final int displayart=0x7f030003;
        public static final int main=0x7f030004;
        public static final int my_location=0x7f030005;
        public static final int preferences=0x7f030006;
        public static final int splash=0x7f030007;
        public static final int webview=0x7f030008;
    }
    public static final class string {
        public static final int activity_ShowImage=0x7f060004;
        public static final int activity_mylocation=0x7f06003f;
        public static final int activity_paint=0x7f060003;
        /**  Preferences strings 
         */
        public static final int activity_preferences=0x7f06002f;
        public static final int app_name=0x7f060000;
        public static final int ar_browser_preferences=0x7f060032;
        public static final int button_draw=0x7f060001;
        public static final int button_ok=0x7f060028;
        public static final int button_view=0x7f060002;
        public static final int cancel=0x7f060014;
        public static final int close=0x7f060011;
        public static final int confirm_reset=0x7f060012;
        public static final int dialog_ar_browser_list=0x7f060035;
        public static final int dialog_brush=0x7f060029;
        public static final int dialog_enter_title=0x7f060015;
        public static final int dialog_loading=0x7f060022;
        public static final int dialog_progress=0x7f06001f;
        public static final int dialog_send=0x7f060017;
        public static final int first_run_dialog_message=0x7f06002c;
        /**  What's new dialog 
         */
        public static final int first_run_dialog_title=0x7f06002b;
        public static final int label_blur=0x7f060027;
        public static final int label_brush_size=0x7f060024;
        public static final int label_color=0x7f06002a;
        public static final int label_color_intensity=0x7f060023;
        public static final int label_emboss=0x7f060026;
        public static final int label_opacity=0x7f060025;
        public static final int landscape=0x7f060016;
        public static final int menu_blur=0x7f060007;
        public static final int menu_brush_size=0x7f060009;
        public static final int menu_color=0x7f060005;
        public static final int menu_credits=0x7f060031;
        public static final int menu_emboss=0x7f060006;
        public static final int menu_erase=0x7f060008;
        public static final int menu_eyedropper=0x7f06000a;
        public static final int menu_mylocation=0x7f060040;
        public static final int menu_preferences=0x7f060030;
        public static final int menu_reset=0x7f06000b;
        public static final int menu_send=0x7f06000d;
        public static final int menu_undo=0x7f06000c;
        public static final int mylocation_address_title=0x7f06003d;
        public static final int mylocation_detect_title=0x7f06003e;
        public static final int mylocation_enter_location_title=0x7f060047;
        public static final int mylocation_enter_position=0x7f060049;
        public static final int mylocation_get_address=0x7f060046;
        public static final int mylocation_get_position=0x7f060045;
        public static final int mylocation_latitude=0x7f060041;
        public static final int mylocation_longitude=0x7f060042;
        public static final int mylocation_select_on_map=0x7f060048;
        public static final int mylocation_select_source=0x7f060044;
        /**  My Location strings 
         */
        public static final int mylocation_title=0x7f06003c;
        public static final int mylocation_validate=0x7f060043;
        public static final int no=0x7f060010;
        public static final int ok=0x7f06000e;
        public static final int preference_mylocation=0x7f06003b;
        public static final int preferences_browser=0x7f060039;
        public static final int preferences_browser_title=0x7f060037;
        public static final int preferences_change_browser=0x7f06003a;
        public static final int preferences_location_title=0x7f060038;
        public static final int preferences_title=0x7f060036;
        public static final int send=0x7f060013;
        public static final int send_approximate_location_found=0x7f06001c;
        public static final int send_button_mylocation=0x7f06001e;
        public static final int send_button_send=0x7f06001d;
        public static final int send_search_gps=0x7f060018;
        public static final int send_search_gps_found=0x7f060019;
        public static final int send_search_gps_not_found=0x7f06001a;
        public static final int send_search_gps_not_found_use_mylocation=0x7f06001b;
        public static final int summary_ar_browser_list=0x7f060034;
        public static final int title_ar_browser_list=0x7f060033;
        public static final int upload_failed=0x7f060021;
        public static final int upload_successful=0x7f060020;
        public static final int whats_new_dialog_message=0x7f06002e;
        public static final int whats_new_dialog_title=0x7f06002d;
        public static final int yes=0x7f06000f;
    }
    public static final class style {
        public static final int tagCheckBox=0x7f070003;
        public static final int tagDialogTheme=0x7f070000;
        public static final int tagEditText=0x7f070002;
        public static final int tagLayout=0x7f070001;
        public static final int tagTextNormal=0x7f070004;
        public static final int tagTextTitle=0x7f070005;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
