/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package org.artags.android.app;

public final class R {
    public static final class anim {
        public static final int disappear=0x7f040000;
        public static final int grow_from_bottom=0x7f040001;
        public static final int grow_from_bottomleft_to_topright=0x7f040002;
        public static final int grow_from_bottomright_to_topleft=0x7f040003;
        public static final int grow_from_top=0x7f040004;
        public static final int grow_from_topleft_to_bottomright=0x7f040005;
        public static final int grow_from_topright_to_bottomleft=0x7f040006;
        public static final int pump_bottom=0x7f040007;
        public static final int pump_top=0x7f040008;
        public static final int shrink_from_bottom=0x7f040009;
        public static final int shrink_from_bottomleft_to_topright=0x7f04000a;
        public static final int shrink_from_bottomright_to_topleft=0x7f04000b;
        public static final int shrink_from_top=0x7f04000c;
        public static final int shrink_from_topleft_to_bottomright=0x7f04000d;
        public static final int shrink_from_topright_to_bottomleft=0x7f04000e;
    }
    public static final class array {
        public static final int ar_browsers_entries=0x7f060000;
        public static final int ar_browsers_entryvalues=0x7f060001;
        public static final int credits=0x7f060002;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int action_item_btn=0x7f020000;
        public static final int action_item_selected=0x7f020001;
        public static final int arrow_down=0x7f020002;
        public static final int arrow_up=0x7f020003;
        public static final int background=0x7f020004;
        public static final int background_artags=0x7f020005;
        public static final int background_land=0x7f020006;
        public static final int bt_display=0x7f020007;
        public static final int bt_display_down=0x7f020008;
        public static final int bt_display_up=0x7f020009;
        public static final int bt_draw=0x7f02000a;
        public static final int bt_draw_down=0x7f02000b;
        public static final int bt_draw_up=0x7f02000c;
        public static final int ic_menu_button=0x7f02000d;
        public static final int icon=0x7f02000e;
        public static final int marker=0x7f02000f;
        public static final int menu_brush_small=0x7f020010;
        public static final int menu_color=0x7f020011;
        public static final int menu_color_small=0x7f020012;
        public static final int menu_credits_small=0x7f020013;
        public static final int menu_erase_small=0x7f020014;
        public static final int menu_eyedropper_small=0x7f020015;
        public static final int menu_preferences_small=0x7f020016;
        public static final int menu_reset_small=0x7f020017;
        public static final int menu_send_small=0x7f020018;
        public static final int menu_undo_small=0x7f020019;
        public static final int popup=0x7f02001a;
        public static final int progress=0x7f02001b;
        public static final int selection_menu_bg=0x7f02001c;
        public static final int selection_menu_bg_pressed=0x7f02001d;
        public static final int splash=0x7f02001e;
        public static final int splash_land=0x7f02001f;
    }
    public static final class id {
        public static final int arrow_down=0x7f090030;
        public static final int arrow_up=0x7f09002f;
        public static final int brush_size=0x7f090006;
        public static final int button_config=0x7f09001b;
        public static final int button_credits=0x7f09001c;
        public static final int button_display=0x7f090015;
        public static final int button_draw=0x7f090014;
        public static final int button_ok=0x7f09000a;
        public static final int button_send=0x7f09001a;
        public static final int button_tools=0x7f090018;
        public static final int button_undo=0x7f090019;
        public static final int checkbox_landscape=0x7f09000e;
        public static final int color_intensity=0x7f090002;
        public static final int dialog_title=0x7f09000b;
        public static final int displayartImageView01=0x7f090013;
        public static final int edit_title=0x7f09000d;
        public static final int footer_organize=0x7f090017;
        public static final int icon=0x7f090000;
        public static final int label_title=0x7f09000c;
        public static final int mylocation_address=0x7f090025;
        public static final int mylocation_address_title=0x7f090024;
        public static final int mylocation_cancel_button=0x7f09002c;
        public static final int mylocation_detect_title=0x7f09001f;
        public static final int mylocation_form=0x7f090021;
        public static final int mylocation_get_position_button=0x7f090023;
        public static final int mylocation_latitude=0x7f090027;
        public static final int mylocation_latitude_label=0x7f090026;
        public static final int mylocation_layout=0x7f09001d;
        public static final int mylocation_longitude=0x7f090029;
        public static final int mylocation_longitude_label=0x7f090028;
        public static final int mylocation_progress=0x7f090020;
        public static final int mylocation_select_source_button=0x7f090022;
        public static final int mylocation_title=0x7f09001e;
        public static final int mylocation_validate=0x7f09002a;
        public static final int mylocation_validate_button=0x7f09002b;
        public static final int opacity=0x7f090004;
        public static final int preferences_browser=0x7f090035;
        public static final int preferences_browser_label=0x7f090034;
        public static final int preferences_browser_title=0x7f090033;
        public static final int preferences_button_change_browser=0x7f090036;
        public static final int preferences_button_close=0x7f090039;
        public static final int preferences_checkbox_mylocation=0x7f090038;
        public static final int preferences_layout=0x7f090031;
        public static final int preferences_location_title=0x7f090037;
        public static final int preferences_title=0x7f090032;
        public static final int root=0x7f090016;
        public static final int scroller=0x7f09002d;
        public static final int seek_brush_size=0x7f090007;
        public static final int seek_intensity=0x7f090003;
        public static final int seek_opacity=0x7f090005;
        public static final int send_cancel_button=0x7f090012;
        public static final int send_search_location=0x7f09000f;
        public static final int send_search_location_progress=0x7f090010;
        public static final int send_send_button=0x7f090011;
        public static final int splash=0x7f09003a;
        public static final int title=0x7f090001;
        public static final int toggleBlur=0x7f090009;
        public static final int toggleEmboss=0x7f090008;
        public static final int tracks=0x7f09002e;
    }
    public static final class layout {
        public static final int action_item=0x7f030000;
        public static final int dialog_brush=0x7f030001;
        public static final int dialog_send=0x7f030002;
        public static final int displayart=0x7f030003;
        public static final int main=0x7f030004;
        public static final int menu_draw=0x7f030005;
        public static final int menu_main=0x7f030006;
        public static final int my_location=0x7f030007;
        public static final int popup=0x7f030008;
        public static final int preferences=0x7f030009;
        public static final int splash=0x7f03000a;
    }
    public static final class string {
        public static final int activity_ShowImage=0x7f07000a;
        public static final int activity_mylocation=0x7f07004a;
        public static final int activity_paint=0x7f070009;
        /**  Preferences strings 
         */
        public static final int activity_preferences=0x7f07003a;
        public static final int app_name=0x7f070000;
        public static final int ar_browser_preferences=0x7f07003d;
        public static final int button_download=0x7f070008;
        public static final int button_draw=0x7f070004;
        public static final int button_ok=0x7f07002f;
        public static final int button_view=0x7f070005;
        public static final int cancel=0x7f07001b;
        public static final int close=0x7f070018;
        public static final int confirm_reset=0x7f070019;
        /**  Credits infos 
         */
        public static final int credits_app_name=0x7f070038;
        public static final int credits_current_version=0x7f070039;
        public static final int dialog_ar_browser_list=0x7f070040;
        public static final int dialog_brush=0x7f070030;
        public static final int dialog_enter_title=0x7f07001c;
        public static final int dialog_loading=0x7f070029;
        public static final int dialog_progress=0x7f070026;
        public static final int dialog_send=0x7f07001e;
        public static final int draw_readme_text=0x7f070037;
        public static final int draw_readme_title=0x7f070036;
        public static final int eula_button_accept=0x7f070002;
        public static final int eula_button_refuse=0x7f070003;
        public static final int eula_title=0x7f070001;
        public static final int first_run_dialog_message=0x7f070033;
        /**  What's new dialog 
         */
        public static final int first_run_dialog_title=0x7f070032;
        public static final int label_blur=0x7f07002e;
        public static final int label_brush_size=0x7f07002b;
        public static final int label_color=0x7f070031;
        public static final int label_color_intensity=0x7f07002a;
        public static final int label_emboss=0x7f07002d;
        public static final int label_opacity=0x7f07002c;
        public static final int landscape=0x7f07001d;
        public static final int menu_blur=0x7f07000e;
        public static final int menu_brush_size=0x7f070010;
        public static final int menu_color=0x7f07000c;
        public static final int menu_credits=0x7f07003c;
        public static final int menu_emboss=0x7f07000d;
        public static final int menu_erase=0x7f07000f;
        public static final int menu_eyedropper=0x7f070011;
        public static final int menu_mylocation=0x7f07004b;
        public static final int menu_preferences=0x7f07003b;
        public static final int menu_reset=0x7f070012;
        public static final int menu_send=0x7f070014;
        public static final int menu_tools=0x7f07000b;
        public static final int menu_undo=0x7f070013;
        public static final int message_browser_not_found=0x7f070007;
        public static final int mylocation_address_title=0x7f070048;
        public static final int mylocation_detect_title=0x7f070049;
        public static final int mylocation_enter_location_title=0x7f070052;
        public static final int mylocation_enter_position=0x7f070054;
        public static final int mylocation_get_address=0x7f070051;
        public static final int mylocation_get_position=0x7f070050;
        public static final int mylocation_latitude=0x7f07004c;
        public static final int mylocation_longitude=0x7f07004d;
        public static final int mylocation_select_on_map=0x7f070053;
        public static final int mylocation_select_source=0x7f07004f;
        /**  My Location strings 
         */
        public static final int mylocation_title=0x7f070047;
        public static final int mylocation_validate=0x7f07004e;
        public static final int no=0x7f070017;
        public static final int ok=0x7f070015;
        public static final int preference_mylocation=0x7f070046;
        public static final int preferences_browser=0x7f070044;
        public static final int preferences_browser_title=0x7f070042;
        public static final int preferences_change_browser=0x7f070045;
        public static final int preferences_location_title=0x7f070043;
        public static final int preferences_title=0x7f070041;
        public static final int send=0x7f07001a;
        public static final int send_approximate_location_found=0x7f070023;
        public static final int send_button_mylocation=0x7f070025;
        public static final int send_button_send=0x7f070024;
        public static final int send_search_gps=0x7f07001f;
        public static final int send_search_gps_found=0x7f070020;
        public static final int send_search_gps_not_found=0x7f070021;
        public static final int send_search_gps_not_found_use_mylocation=0x7f070022;
        public static final int share_chooser_title=0x7f070057;
        public static final int share_pattern=0x7f070056;
        public static final int summary_ar_browser_list=0x7f07003f;
        public static final int title_ar_browser_list=0x7f07003e;
        public static final int title_browser_not_found=0x7f070006;
        public static final int tweet_pattern=0x7f070055;
        public static final int upload_failed=0x7f070028;
        public static final int upload_successful=0x7f070027;
        public static final int whats_new_dialog_message=0x7f070035;
        public static final int whats_new_dialog_title=0x7f070034;
        public static final int yes=0x7f070016;
    }
    public static final class style {
        /**  MENU 
         */
        public static final int Animations=0x7f080006;
        /**  PopDownMenu 
         */
        public static final int Animations_PopDownMenu=0x7f080007;
        public static final int Animations_PopDownMenu_Center=0x7f080008;
        public static final int Animations_PopDownMenu_Left=0x7f080009;
        public static final int Animations_PopDownMenu_Reflect=0x7f08000b;
        public static final int Animations_PopDownMenu_Right=0x7f08000a;
        /**  PopUpMenu 
         */
        public static final int Animations_PopUpMenu=0x7f08000c;
        public static final int Animations_PopUpMenu_Center=0x7f08000d;
        public static final int Animations_PopUpMenu_Left=0x7f08000e;
        public static final int Animations_PopUpMenu_Reflect=0x7f080010;
        public static final int Animations_PopUpMenu_Right=0x7f08000f;
        public static final int tagCheckBox=0x7f080003;
        public static final int tagDialogTheme=0x7f080000;
        public static final int tagEditText=0x7f080002;
        public static final int tagLayout=0x7f080001;
        public static final int tagTextNormal=0x7f080004;
        public static final int tagTextTitle=0x7f080005;
    }
    public static final class xml {
        public static final int preferences=0x7f050000;
    }
}
