/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.artgameweekend.projects.art;

public final class R {
    public static final class attr {
    }
    public static final class drawable {
        public static final int bt_display=0x7f020000;
        public static final int bt_draw=0x7f020001;
        public static final int icon=0x7f020002;
    }
    public static final class id {
        public static final int button_display=0x7f050001;
        public static final int button_draw=0x7f050000;
        public static final int button_view=0x7f050002;
    }
    public static final class layout {
        public static final int main=0x7f030000;
        public static final int send=0x7f030001;
    }
    public static final class string {
        public static final int activity_paint=0x7f040003;
        public static final int app_name=0x7f040000;
        public static final int button_draw=0x7f040001;
        public static final int button_view=0x7f040002;
        public static final int menu_blur=0x7f040006;
        public static final int menu_color=0x7f040004;
        public static final int menu_emboss=0x7f040005;
        public static final int menu_erase=0x7f040007;
        public static final int menu_send=0x7f040009;
        public static final int menu_srcatop=0x7f040008;
    }
}
