/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package com.artgameweekend.projects.art;

public final class R {
    public static final class array {
        public static final int ar_browsers_entries=0x7f050000;
        public static final int ar_browsers_entryvalues=0x7f050001;
    }
    public static final class attr {
    }
    public static final class drawable {
        public static final int bt_display=0x7f020000;
        public static final int bt_display_down=0x7f020001;
        public static final int bt_draw=0x7f020002;
        public static final int bt_draw_down=0x7f020003;
        public static final int credits=0x7f020004;
        public static final int icon=0x7f020005;
        public static final int menu_blur=0x7f020006;
        public static final int menu_brush=0x7f020007;
        public static final int menu_color=0x7f020008;
        public static final int menu_emboss=0x7f020009;
        public static final int menu_erase=0x7f02000a;
        public static final int menu_save=0x7f02000b;
        public static final int splash=0x7f02000c;
        public static final int splash_land=0x7f02000d;
    }
    public static final class id {
        public static final int brush_size=0x7f070003;
        public static final int button_display=0x7f07000d;
        public static final int button_draw=0x7f07000c;
        public static final int button_ok=0x7f070007;
        public static final int checkbox_landscape=0x7f07000a;
        public static final int color_intensity=0x7f070001;
        public static final int credits=0x7f070000;
        public static final int displayartImageView01=0x7f07000b;
        public static final int edit_title=0x7f070009;
        public static final int label_title=0x7f070008;
        public static final int seek_brush_size=0x7f070004;
        public static final int seek_intensity=0x7f070002;
        public static final int splash=0x7f07000e;
        public static final int toggleBlur=0x7f070006;
        public static final int toggleEmboss=0x7f070005;
        public static final int webview=0x7f07000f;
    }
    public static final class layout {
        public static final int credits=0x7f030000;
        public static final int dialog_brush=0x7f030001;
        public static final int dialog_send=0x7f030002;
        public static final int displayart=0x7f030003;
        public static final int main=0x7f030004;
        public static final int send=0x7f030005;
        public static final int splash=0x7f030006;
        public static final int webview=0x7f030007;
    }
    public static final class string {
        public static final int activity_SaveFile=0x7f060005;
        public static final int activity_ShowImage=0x7f060004;
        public static final int activity_paint=0x7f060003;
        /**  Preferences strings 
         */
        public static final int activity_preferences=0x7f06001e;
        public static final int app_name=0x7f060000;
        public static final int ar_browser_preferences=0x7f060021;
        public static final int button_draw=0x7f060001;
        public static final int button_ok=0x7f06001b;
        public static final int button_view=0x7f060002;
        public static final int cancel=0x7f06000f;
        public static final int dialog_ar_browser_list=0x7f060024;
        public static final int dialog_brush=0x7f06001c;
        public static final int dialog_enter_title=0x7f060010;
        public static final int dialog_loading=0x7f060016;
        public static final int dialog_progress=0x7f060013;
        public static final int dialog_send=0x7f060012;
        public static final int label_blur=0x7f06001a;
        public static final int label_brush_size=0x7f060018;
        public static final int label_color=0x7f06001d;
        public static final int label_color_intensity=0x7f060017;
        public static final int label_emboss=0x7f060019;
        public static final int landscape=0x7f060011;
        public static final int menu_blur=0x7f060008;
        public static final int menu_brush_size=0x7f06000a;
        public static final int menu_color=0x7f060006;
        public static final int menu_credits=0x7f060020;
        public static final int menu_emboss=0x7f060007;
        public static final int menu_erase=0x7f060009;
        public static final int menu_preferences=0x7f06001f;
        public static final int menu_send=0x7f06000c;
        public static final int menu_srcatop=0x7f06000b;
        public static final int ok=0x7f06000d;
        public static final int send=0x7f06000e;
        public static final int summary_ar_browser_list=0x7f060023;
        public static final int title_ar_browser_list=0x7f060022;
        public static final int upload_failed=0x7f060015;
        public static final int upload_successful=0x7f060014;
    }
    public static final class xml {
        public static final int preferences=0x7f040000;
    }
}
